package:
  name: gubbins
  version: '2.2.0'

source:
  git_url: https://github.com/sanger-pathogens/gubbins.git
  git_rev: v2.2.0

build:
  number: 0
  skip: True  # [py27]
  skip: True  # [osx]

requirements:
  build:
    - python >=3.5
    - setuptools
    - pip
    - autoconf
    - automake
    - libtool
    - pkg-config
    - nose
    - reportlab
    - dendropy >=4.0
    - biopython ==1.65
    - pillow
    - zlib
    - certifi

  run:
    - python >=3.5
    - setuptools
    - pip
    - nose
    - reportlab
    - dendropy >=4.0
    - biopython ==1.65
    - certifi
    - pillow
    - libgcc
    - zlib
    - fasttree
    - raxml >=8.0   

test:
  commands:
    - run_gubbins.py -h

about:
  home: https://github.com/sanger-pathogens/gubbins
  license: "GPLv2"
  summary: "Rapid phylogenetic analysis of large samples of recombinant bacterial whole genome sequences using Gubbins"
